In [1]:
import pandas as pd

customers = pd.read_csv("customers.csv")
events = pd.read_csv("events.csv")
order_items = pd.read_csv("order_items.csv")
orders = pd.read_csv("orders.csv")
products = pd.read_csv("products.csv")
reviews = pd.read_csv("reviews.csv")
sessions = pd.read_csv("sessions.csv")

In [2]:
customers.head()

,customer_id,name,email,country,age,signup_date,marketing_opt_in
0,1,Jennifer Salinas,nicholas59@example.org,JP,71,2020-09-04,True
1,2,Phillip Ramos,christinarubio@example.com,IN,26,2020-04-05,False
2,3,Dawn Fowler,jessica03@example.org,BR,21,2023-08-31,True
3,4,Mario Butler,paula27@example.org,FR,63,2022-06-30,True
4,5,Amber Brown,kevin85@example.net,BR,19,2022-07-22,True

In [3]:
customers.shape

(20000, 7)

In [4]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   name              20000 non-null  object
 2   email             20000 non-null  object
 3   country           20000 non-null  object
 4   age               20000 non-null  int64
 5   signup_date       20000 non-null  object
 6   marketing_opt_in  20000 non-null  bool
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB

In [5]:
customers['customer_id'].nunique()

20000

In [6]:
customers['customer_id'].duplicated().sum()

np.int64(0)

In [7]:
customers['country'].value_counts()

country
US    3648
IN    1589
GB    1585
BR    1421
DE    1397
FR    1325
MX    1206
AU    1045
CA    1015
JP     974
ES     950
NL     874
SG     797
SE     621
PL     605
AE     560
ZA     388
Name: count, dtype: int64

In [8]:
customers['age'].describe()

count    20000.000000
mean        46.492550
std         16.767961
min         18.000000
25%         32.000000
50%         46.500000
75%         61.000000
max         75.000000
Name: age, dtype: float64

In [9]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'])

In [2]:
events.head()

,event_id,session_id,timestamp,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd
0,1,1,2021-12-27T00:08:36,page_view,93.0,NaN,NaN,NaN,NaN,NaN
1,2,1,2021-12-27T00:16:36,page_view,1005.0,NaN,NaN,NaN,NaN,NaN
2,3,1,2021-12-27T00:18:01,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN
3,4,1,2021-12-27T00:45:36,page_view,918.0,NaN,NaN,NaN,NaN,NaN
4,5,1,2021-12-27T01:03:36,page_view,946.0,NaN,NaN,NaN,NaN,NaN

In [2]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   event_id      760958 non-null  int64
 1   session_id    760958 non-null  int64
 2   timestamp     760958 non-null  object
 3   event_type    760958 non-null  object
 4   product_id    682469 non-null  float64
 5   qty           143126 non-null  float64
 6   cart_size     44909 non-null   float64
 7   payment       33580 non-null   object
 8   discount_pct  33580 non-null   float64
 9   amount_usd    33580 non-null   float64
dtypes: float64(5), int64(2), object(3)
memory usage: 58.1+ MB

In [3]:
events['timestamp'] = pd.to_datetime(events['timestamp'])

In [4]:
events['event_type'].value_counts()

event_type
page_view      539343
add_to_cart    143126
checkout        44909
purchase        33580
Name: count, dtype: int64

In [5]:
events['event_id'].nunique()

760958

In [6]:
events['session_id'].nunique()

120000

In [16]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33580 entries, 0 to 33579
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        33580 non-null  int64
 1   customer_id     33580 non-null  int64
 2   order_time      33580 non-null  object
 3   payment_method  33580 non-null  object
 4   discount_pct    33580 non-null  int64
 5   subtotal_usd    33580 non-null  float64
 6   total_usd       33580 non-null  float64
 7   country         33580 non-null  object
 8   device          33580 non-null  object
 9   source          33580 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 2.6+ MB

In [17]:
orders['order_time'] = pd.to_datetime(orders['order_time'])

In [18]:
orders['order_id'].nunique()

33580

In [19]:
orders['order_id'].duplicated().sum()

np.int64(0)

In [20]:
orders['customer_id'].nunique()

16268

In [21]:
orders['payment_method'].value_counts()

payment_method
card      23455
paypal     5032
wallet     3373
cod        1720
Name: count, dtype: int64

In [22]:
orders['device'].value_counts()

device
mobile     18469
desktop    12750
tablet      2361
Name: count, dtype: int64

In [23]:
orders['source'].value_counts()

source
organic     11268
direct       8387
paid         4121
social       4024
email        3056
referral     2724
Name: count, dtype: int64

In [24]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59163 entries, 0 to 59162
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        59163 non-null  int64
 1   product_id      59163 non-null  int64
 2   unit_price_usd  59163 non-null  float64
 3   quantity        59163 non-null  int64
 4   line_total_usd  59163 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 2.3 MB

In [25]:
order_items['order_id'].nunique()

33580

In [26]:
order_items['product_id'].nunique()

1195

In [27]:
order_items.isnull().sum()

order_id          0
product_id        0
unit_price_usd    0
quantity          0
line_total_usd    0
dtype: int64

In [28]:
order_items['quantity'].describe()

count    59163.000000
mean         1.303281
std          0.786787
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: quantity, dtype: float64

In [29]:
order_items['line_total_usd'].describe()

count    59163.000000
mean        81.733655
std        106.360939
min          3.500000
25%         24.770000
50%         49.920000
75%         98.680000
max       2376.920000
Name: line_total_usd, dtype: float64

In [30]:
(order_items['unit_price_usd'] * order_items['quantity']
 == order_items['line_total_usd']).mean()

np.float64(0.9852610584317901)

In [31]:
check = order_items[
    (order_items['unit_price_usd'] * order_items['quantity']).round(2)
    != order_items['line_total_usd'].round(2)
]

check.shape

(0, 5)

There are no rows where unit_price_usd × quantity differs from line_total_usd after rounding to 2 decimals.

In [32]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  1197 non-null   int64
 1   category    1197 non-null   object
 2   name        1197 non-null   object
 3   price_usd   1197 non-null   float64
 4   cost_usd    1197 non-null   float64
 5   margin_usd  1197 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 56.2+ KB

In [33]:
products.isnull().sum()

product_id    0
category      0
name          0
price_usd     0
cost_usd      0
margin_usd    0
dtype: int64

In [34]:
products['product_id'].nunique()

1197

In [35]:
products['category'].value_counts()

category
Electronics       171
Home & Kitchen    171
Beauty            171
Sports            171
Fashion           171
Books             171
Toys              171
Name: count, dtype: int64

In [36]:
(
    (products['price_usd'] - products['cost_usd']).round(2)
    == products['margin_usd'].round(2)
).mean()

np.float64(1.0)

100% of product rows satisfy price_usd - cost_usd = margin_usd.

In [37]:
sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   session_id   120000 non-null  int64
 1   customer_id  120000 non-null  int64
 2   start_time   120000 non-null  object
 3   device       120000 non-null  object
 4   source       120000 non-null  object
 5   country      120000 non-null  object
dtypes: int64(2), object(4)
memory usage: 5.5+ MB

In [38]:
sessions['start_time'] = pd.to_datetime(sessions['start_time'])

In [39]:
sessions['session_id'].nunique()

120000

In [40]:
sessions['session_id'].duplicated().sum()

np.int64(0)

In [41]:
sessions['customer_id'].nunique()

19945

In [42]:
sessions['device'].value_counts()

device
mobile     65942
desktop    45547
tablet      8511
Name: count, dtype: int64

In [43]:
sessions['source'].value_counts()

source
organic     40776
direct      29861
paid        14465
social      14389
email       10949
referral     9560
Name: count, dtype: int64

In [44]:
sessions['country'].value_counts()

country
US    21913
IN     9567
GB     9451
BR     8573
DE     8332
FR     7811
MX     7286
AU     6443
CA     6057
JP     5841
ES     5580
NL     5261
SG     4780
SE     3702
PL     3630
AE     3424
ZA     2349
Name: count, dtype: int64

In [45]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10780 entries, 0 to 10779
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    10780 non-null  int64
 1   order_id     10780 non-null  int64
 2   product_id   10780 non-null  int64
 3   rating       10780 non-null  int64
 4   review_text  10780 non-null  object
 5   review_time  10780 non-null  object
dtypes: int64(4), object(2)
memory usage: 505.4+ KB

In [46]:
reviews['review_time'] = pd.to_datetime(reviews['review_time'])

In [47]:
reviews.isnull().sum()

review_id      0
order_id       0
product_id     0
rating         0
review_text    0
review_time    0
dtype: int64

In [48]:
reviews['rating'].value_counts().sort_index()

rating
1     423
2     757
3    1980
4    3565
5    4055
Name: count, dtype: int64

In [49]:
reviews['product_id'].nunique()

1140

In [50]:
reviews['order_id'].nunique()

6111

In [51]:
import os

output_folder = "ecommerce_analytics_csv"
os.makedirs(output_folder, exist_ok=True)

customers.to_csv(f"{output_folder}/customers.csv", index=False)
sessions.to_csv(f"{output_folder}/sessions.csv", index=False)
events.to_csv(f"{output_folder}/events.csv", index=False)
orders.to_csv(f"{output_folder}/orders.csv", index=False)
order_items.to_csv(f"{output_folder}/order_items.csv", index=False)
products.to_csv(f"{output_folder}/products.csv", index=False)
reviews.to_csv(f"{output_folder}/reviews.csv", index=False)

print("All files saved successfully!")

All files saved successfully!

In [8]:
events.head()

,event_id,session_id,timestamp,event_type,product_id,qty,cart_size,payment,discount_pct,amount_usd
0,1,1,2021-12-27 00:08:36,page_view,93.0,NaN,NaN,NaN,NaN,NaN
1,2,1,2021-12-27 00:16:36,page_view,1005.0,NaN,NaN,NaN,NaN,NaN
2,3,1,2021-12-27 00:18:01,add_to_cart,1005.0,1.0,NaN,NaN,NaN,NaN
3,4,1,2021-12-27 00:45:36,page_view,918.0,NaN,NaN,NaN,NaN,NaN
4,5,1,2021-12-27 01:03:36,page_view,946.0,NaN,NaN,NaN,NaN,NaN

In [9]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   event_id      760958 non-null  int64
 1   session_id    760958 non-null  int64
 2   timestamp     760958 non-null  datetime64[ns]
 3   event_type    760958 non-null  object
 4   product_id    682469 non-null  float64
 5   qty           143126 non-null  float64
 6   cart_size     44909 non-null   float64
 7   payment       33580 non-null   object
 8   discount_pct  33580 non-null   float64
 9   amount_usd    33580 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(2)
memory usage: 58.1+ MB

In [10]:
events_mysql = events.copy()

# Columns that should be integers but contain missing values
events_mysql['product_id'] = events_mysql['product_id'].astype('Int64')
events_mysql['qty'] = events_mysql['qty'].astype('Int64')
events_mysql['cart_size'] = events_mysql['cart_size'].astype('Int64')

In [11]:
events_mysql = events_mysql.where(pd.notna(events_mysql), None)

In [12]:
events_mysql.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760958 entries, 0 to 760957
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   event_id      760958 non-null  int64
 1   session_id    760958 non-null  int64
 2   timestamp     760958 non-null  datetime64[ns]
 3   event_type    760958 non-null  object
 4   product_id    682469 non-null  Int64
 5   qty           143126 non-null  Int64
 6   cart_size     44909 non-null   Int64
 7   payment       33580 non-null   object
 8   discount_pct  33580 non-null   float64
 9   amount_usd    33580 non-null   float64
dtypes: Int64(3), datetime64[ns](1), float64(2), int64(2), object(2)
memory usage: 60.2+ MB

In [13]:
from sqlalchemy import create_engine

In [14]:
engine = create_engine(
    "mysql+pymysql://root:ishi20020805@localhost:3306/ecommerce_analytics"
)

In [15]:
with engine.connect() as conn:
    print("MySQL connection successful!")

MySQL connection successful!

In [17]:
events_mysql.to_sql(
    'events',
    con=engine,
    if_exists='append',
    index=False,
    chunksize=10000,
    method='multi'
)

760958